apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
    - name: web
      image: nginx
      imagePullPolicy: Always
      resources:
        limits:
          memory: "1Gi"
          cpu: "1"
        requests:
          memory: "300Mi"
          cpu: "0.5"